version: '3.3'
services:
  database:
    image: mysql:8.0.18
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: IS_Assignment3
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
